# Target specific macros
ROOT = /nxtOSEK
TOPPERS_OSEK_ROOT_SG = c:/cygwin/nxtOSEK/toppers_osek
TARGET = NXTrike
TARGET_SOURCES = \
	NXTrikeSample.c
TOPPERS_OSEK_OIL_SOURCE = ./NXTrikeSample.oil

# Don't modify below part
O_PATH ?= build
include $(ROOT)/ecrobot/ecrobot.mak
