# Target specific macros
TARGET = MonitorSample
TARGET_SOURCES = \
	Monitor.c
TOPPERS_OSEK_OIL_SOURCE = ./MonitorSample.oil

# Don't modify below part
O_PATH ?= build

include ../../nxtOsek/ecrobot/ecrobot.mak
